branch-defaults:
  main:
    environment: $CIRCLE_BRANCH-my-application
global:
  application_name: Weblalala-env
  default_ec2_keyname: webserver
  default_platform: PHP 8.0 running on 64bit Amazon Linux 2/3.2.0
  default_region: ap-southeast-1
  sc: git